### ISSUE TITLE
Public SSL certs for local.racklab.xyz

### ISSUE THREAD

**Issue by danPixl** [racklab/labHTTP#4]
local.racklab.xyz currently points at localhost (127.0.0.1) for me to develop labHTTP, with certificates from Let's Encrypt.
As SSL is a requirement to use labHTTP, I was thinking about making the cert public, so if you're developing with it, you can grab the keys from the Racklab site and point your `config.js` at them.

Yes, this means making a private key open to the world. However, this would be the most streamlined way to do it, rather than having people make self-signed certs.

**Comment by danPixl** [comment]
bump

**Comment by leo60228** [comment]
This goes against section 3.1 of the [Let's Encrypt Subscriber Agreement](https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf).

**Comment by danPixl** [comment]
Oh, okay then. I'll have to publish a self-signing guide.
